[workspace]
members = ["projects/*"]
default-members = [
    "projects/vos-error",
    "projects/vos-core",
#    "projects/vos-openapi",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"
