[workspace]
members = ["projects/*"]
default-members = [
    "projects/voml-collection",
    "projects/vos-error",
#    "projects/vos-cli",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"
